oracle/nosql-java-sdk

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/ops/TableResult.java, driver/src/test/java/oracle/nosql/driver/BasicTest.java
Fixed a problem where the cloud service might succeed when dropping a table
that does not exist when it should have thrown a TableNotFound exception.
=> TableNotFound exception in cloud

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java, driver/src/main/java/oracle/nosql/driver/ops/TableResult.java
Fix javadoc in NoSQLHandleConfig, modify format in CHANGELOG.md to conform to keepachangelog.
=> Fix javadoc in NoSQLHandleConfig

driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClientHandler.java, driver/src/main/java/oracle/nosql/driver/httpclient/ResponseHandler.java
Fixed a case where received messages may not be released properly if a lot of requests are timing out before their responses are received. This can happen when the netty channel thread receives an older response while a current response is being processed by a driver thread.
The fix is to make sure the channel's state attribute is cleared as soon as the channel handler receives a valid response and notifies the driver thread. The state is also cleared when the driver thread releases the channel.
=> Fixed a case where received messages may not be released properly

driver/src/test/java/oracle/nosql/driver/BasicTest.java, driver/src/test/java/oracle/nosql/driver/OnPremiseTest.java, driver/src/test/java/oracle/nosql/driver/ProxyTestBase.java, driver/src/test/java/oracle/nosql/driver/QueryTest.java
Added logic to manage versions of proxy, kvclient, and kvserver based on
envrionment or properties settings. Used for testing, to skip tests that may not
run properly against older versions. No changes to public APIs.
Version checks in various tests are done with the minimum of client and server kv versions.
The proxy version is not checked. All three values are available to tests if needed.
=> Added logic to manage versions of proxy, kvclient, and kvserver.

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/Version.java, driver/src/test/java/oracle/nosql/driver/BasicTest.java
This allows easy creation of a Version from the return value of the row_version() function in a query.
=> Added Version.createVersion(byte[])

driver/src/test/java/oracle/nosql/driver/BasicTest.java
Modified test to check version semantics instead of direct byte array comparison.
=> Changed test to use version returned by query in put / delete

driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/ops/Request.java, driver/src/main/java/oracle/nosql/driver/ops/Result.java, driver/src/main/java/oracle/nosql/driver/util/HttpConstants.java
The latest proxy with DRL enabled will set a new header in the response if it delays sending the response due to rate limiting. This code change reads that header and adds the value (in milliseconds) to the existing rate limit delay value.
=> Read rate limiter delay from response headers.

driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/iam/SecurityTokenSupplier.java, driver/src/main/java/oracle/nosql/driver/ops/QueryRequest.java, driver/src/main/java/oracle/nosql/driver/ops/TableResult.java
In some Instance Principal cases, the security token returned from OCI Identity may have a very short expiration. This change removes the expiration check, and allows a single retry on requests that get specific authN errors.
It also adds trace-level logging of authentication token details.
=> Retry request on specific authentication errors.

driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/test/java/oracle/nosql/driver/QueryTest.java
This change ensures that the timeout sent to the server is always the amount of time remaining before the overall request times out, regardless of internal retries and/or internal rate limiting.
Also updated low throughput test to not take too long when server-side rate limiting is in place.
=> Fixed an issue with timeouts.

driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java, driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/http/NoSQLHandleImpl.java, driver/src/main/java/oracle/nosql/driver/util/HttpConstants.java
Methods are hidden for now.
Requires onprem KV version 22.3, patch revision 24 or higher.
=> Added methods to set default namespace (onprem only)

driver/pom.xml, driver/src/test/java/oracle/nosql/driver/iam/InstancePrincipalsProviderTest.java, driver/src/test/java/oracle/nosql/driver/iam/ResourcePrincipalProviderTest.java
The newer Bouncy Castle versions moved test code to a different artifact. Include that for testing.
Also remove Instance and Resource Principal (local) tests that are no longer relevant
=> Add new test-only Bouncy Castle dependency

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/DefaultRetryHandler.java, driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java, driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/ops/DeleteRequest.java, driver/src/main/java/oracle/nosql/driver/ops/GetIndexesRequest.java, driver/src/main/java/oracle/nosql/driver/ops/GetRequest.java, driver/src/main/java/oracle/nosql/driver/ops/GetTableRequest.java, driver/src/main/java/oracle/nosql/driver/ops/ListTablesRequest.java, driver/src/main/java/oracle/nosql/driver/ops/MultiDeleteRequest.java, driver/src/main/java/oracle/nosql/driver/ops/PrepareRequest.java, driver/src/main/java/oracle/nosql/driver/ops/PutRequest.java, driver/src/main/java/oracle/nosql/driver/ops/QueryRequest.java, driver/src/main/java/oracle/nosql/driver/ops/Request.java, driver/src/main/java/oracle/nosql/driver/ops/SystemRequest.java, driver/src/main/java/oracle/nosql/driver/ops/SystemStatusRequest.java, driver/src/main/java/oracle/nosql/driver/ops/TableRequest.java, driver/src/main/java/oracle/nosql/driver/ops/TableResult.java, driver/src/main/java/oracle/nosql/driver/ops/TableUsageRequest.java, driver/src/main/java/oracle/nosql/driver/ops/WriteMultipleRequest.java, driver/src/test/java/oracle/nosql/driver/OnPremiseTest.java
Added per-request namespace capability (on-premises only).
Also modified internal timing to use nanoTime() instead of
currentTimeMillis(), which can go backwards in specific instances,
and made per-request-iteration timeout values more accurate.
=> Added per-request namespace capability (on-premises only).

driver/src/main/java/oracle/nosql/driver/ops/Request.java, driver/src/test/java/oracle/nosql/driver/OnPremiseTest.java, driver/src/test/java/oracle/nosql/driver/ProxyTestBase.java
Added copying of namespace to new request object.
=> Fixed issue with namespaces in copied requests.

driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/util/SimpleRateLimiter.java
Also updated regular timeout message to not show requestId if it is empty (to avoid confusion).
=> Updated rate limiter timeout message.

driver/src/main/java/oracle/nosql/driver/http/Stats.java, driver/src/main/java/oracle/nosql/driver/http/StatsControlImpl.java
Avoid NPE when stats logger doesn't have a level set.
=> Avoid NPE when level is not set for stats logger.

driver/src/main/java/oracle/nosql/driver/values/NumberValue.java
This was picked up by an internal test failure. It is the result of using BigDecimal directly inside Number
=> Fix comparison of BigDecimal values to use compareTo() instead of equals

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/RetryableException.java, driver/src/main/java/oracle/nosql/driver/SecurityInfoNotReadyException.java, driver/src/main/java/oracle/nosql/driver/httpclient/ConnectionPool.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClientChannelPoolHandler.java, driver/src/main/java/oracle/nosql/driver/iam/SecurityTokenSupplier.java, driver/src/main/java/oracle/nosql/driver/util/HttpRequestUtil.java
- close and remove channel from queue on "inactive" notification
- set promise to failed if channel is inactive
- added cause to AuthInfoNotReady exception
- add host, port, uri to timeout exception message
=> Cleaned up "inactive channel" auth logic.

driver/src/main/java/oracle/nosql/driver/ops/AddReplicaRequest.java, driver/src/main/java/oracle/nosql/driver/ops/DropReplicaRequest.java
Add/Drop requests are table request, the time out should default to table request time out.
=> Use default table request time out for add/drop replica requests.

driver/pom.xml
This is to address the LDAP injection vulerability discussed at https://github.com/oracle/nosql-java-sdk/security/dependabot/4
=> Updated bcprov to bcprov-jdk18on-1.76

driver/pom.xml, driver/scripts/generate_version_strings.sh, driver/src/main/java/oracle/nosql/driver/DriverMain.java, driver/src/main/java/oracle/nosql/driver/NoSQLException.java, driver/src/main/java/oracle/nosql/driver/SDKVersion.java, driver/src/test/java/oracle/nosql/driver/HandleConfigTest.java
The version is extracted from the pom file and put into SDKVersion.java. The old method that looked in the manifest now uses SDKVersion.
=> Added sdk version to exception messages

driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/iam/SignatureProvider.java, driver/src/main/java/oracle/nosql/driver/ops/Request.java
The Request.oboToken is only required by Java SDK for internal cross-region request, it is not necessary for other drivers. Add comments to Request.oboToken and its callers to clarify this.
=> Update comments related to Request.oboToken to clarify that it is only required by Java SDK

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java
Don't use the default Netty "quiet time" when shutting down the worker group. This also affects cloud service authentication methods that use HTTP requests to acquire authentication information, such as Instance Principal
=> Fix performance of handle close

driver/src/main/java/oracle/nosql/driver/kv/StoreAccessTokenProvider.java
Don't login again if, after waiting for on-premises kv login the auth string has been fetched
=> Re-check on-premises auth string while under lock

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/NoSQLHandle.java, driver/src/main/java/oracle/nosql/driver/http/StatsControlImpl.java, driver/src/test/java/oracle/nosql/driver/BasicTest.java, driver/src/test/java/oracle/nosql/driver/ProxyTestBase.java, driver/src/test/java/oracle/nosql/driver/WriteMultipleTest.java
o. Updated JavaDoc for Put and Delete APIs
o. Updated tests for new put and delete semantics. Tests will use proxy serial version in
the response to detect proxy version and test for old and new behaviour
o. Fixed debug logging issue when stats collection is enabled 
o. Updated CHANGELOG.md
Testing:
Tested against proxies with version V5, V4 and V3
=> Put and Delete new semantics

driver/pom.xml
When use Instance Principal Auth to run functional test(nosql-drvier 5.4.15), got java.lang.NoClassDefFoundError: org/bouncycastle/asn1/oiw/OIWObjectIdentifiers error, and the nosql-drvier 5.4.15 uses bouncy-castle 1.78. （see discussion in slack https://proddev-database.slack.com/archives/C9A0HCEMP/p1726487223705179?thread_ts=1726158296.764489&cid=C9A0HCEMP)
Bouncycastle has changed the packaging since 1.78, the org/bouncycastle/asn1/*.class are moved to bcutil-jdk18on.jar, so need include bcutil-jdk18on.jar into the dependencies of nosql driver.
In driver/pom.xml, all the dependencies of bcprov-jdk18on and bcpkix-jdk18on are explicitly excluded, and the bcutil-jdk18on is dependency for test scope only. The bcutil-jdk18on and bcprov-jdk18on are only dependencies of bcpkix-jdk18on, and no …
=> Include bcutil-jdk18on.jar into the dependencies.

driver/src/main/java/oracle/nosql/driver/util/NettyByteInputStream.java, driver/src/main/java/oracle/nosql/driver/util/PackedInteger.java, driver/src/main/java/oracle/nosql/driver/util/SerializationUtil.java, driver/src/main/java/oracle/nosql/driver/values/MapWalker.java
The serialization code assumed that a non-direct Netty ByteBuf has a single contiguous byte array backing it and that is not the case. Remove the optimization for this case.
=> Fix serialization problem using heap based netty ByteBuf

CHANGELOG.md, THIRD_PARTY_LICENSES.txt, driver/pom.xml, driver/src/main/java/oracle/nosql/driver/iam/OkeWorkloadIdentityProvider.java, driver/src/main/java/oracle/nosql/driver/iam/PrivateKeyProvider.java, driver/src/main/java/oracle/nosql/driver/iam/ResourcePrincipalTokenSupplier.java, driver/src/main/java/oracle/nosql/driver/iam/SecurityTokenSupplier.java, driver/src/main/java/oracle/nosql/driver/iam/Utils.java, driver/src/main/java/oracle/nosql/driver/iam/pki/Eraser.java, driver/src/main/java/oracle/nosql/driver/iam/pki/Hex.java, driver/src/main/java/oracle/nosql/driver/iam/pki/OpenSslPbeSecretKeyFactory.java, driver/src/main/java/oracle/nosql/driver/iam/pki/OpenSslPbeSecretKeyGenerator.java, driver/src/main/java/oracle/nosql/driver/iam/pki/Pem.java, driver/src/main/java/oracle/nosql/driver/iam/pki/PemEncryptedKeyException.java, driver/src/main/java/oracle/nosql/driver/iam/pki/PemEncryptionException.java, driver/src/main/java/oracle/nosql/driver/iam/pki/PemException.java, driver/src/main/java/oracle/nosql/driver/iam/pki/Pkcs1EncryptedPrivateKeyInfo.java, driver/src/main/java/oracle/nosql/driver/iam/pki/Sensitive.java, driver/src/main/java/oracle/nosql/driver/iam/pki/Text.java, driver/src/main/java/oracle/nosql/driver/iam/pki/Utf8.java, driver/src/main/java/oracle/nosql/driver/iam/pki/package-info.java, driver/src/test/java/oracle/nosql/driver/DriverTestBase.java, driver/src/test/java/oracle/nosql/driver/iam/InstancePrincipalsProviderTest.java
- replaced the bouncy castle libraries with PEM utility classes from oci-java-sdk written in standard Java JCE APIs due to the CVE problems found in security scans.
- changed the exception thrown in Instance/Resource/OKE principal providers for invalid security token from IllegalArgumentException to SecurityInfoNotReadyException. We have seen a security token issued by IAM failed the local token validation in production region, the only action to take is to retry in this case.
=> Remove bouncy castle and change the exception for invalid security token

CHANGELOG.md
Move the change log for PrepareQueryException from 5.4.16 to [Unreleased] section, because 5.4.16 has been released.
=> Move the change log for PrepareQueryException to [Unreleased] section.

driver/src/test/java/oracle/nosql/driver/ProxyTestBase.java, driver/src/test/java/oracle/nosql/driver/QueryTest.java
A test fix about the expected Exception caught from query prepared before table is evolved.
=> A test fix about the expected Exception caught from query prepared before table is evolved.

driver/src/main/java/oracle/nosql/driver/ops/QueryRequest.java
Changes to java doc of QueryRequest.setLimit(), it is used to set update limit  for update query in onprem.
=> Changes to java doc of QueryRequest.setLimit()

driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonProtocol.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonSerializerFactory.java, driver/src/main/java/oracle/nosql/driver/query/VirtualScan.java
In the context of the inner joins work I simplified the VirtualScan info shipped between the proxy and the sdks: instead of sending the full KV VirtualScan, only the sid and pid were sent. The rational was that the full VirtualScan info is also contained in the continuation key and, at the proxy, it can be obtained from the continuation key. However, this does not work for sorting queries, because in this case, there is a separate continuation key for each shard. When a new virtual scan is created for a shard, the sdk must send a null continuation key to the proxy for the 1st batch of this scan. So, in this case, the proxy must receive the full VirtualScan separately.
=> reverted VirtualScan simplification and added join-related info to VirtualScan

CHANGELOG.md, README.md, driver/pom.xml, driver/src/main/java/oracle/nosql/driver/SDKVersion.java, examples/pom.xml, pom.xml
- PrepareQueryException. This exception is thrown if a prepared query is
executed after (a) the index used by the query has been dropped and then
re-created with a different schema, or (b) one or more of the referenced
tables has been altered (via the alter table statement). It is only used
with server 25.1 or higher that supports it.
- Update netty dependency to 4.1.118.Final
=> Preparing for 5.4.17 release

CHANGELOG.md, driver/pom.xml, driver/src/main/java/oracle/nosql/driver/SDKVersion.java, driver/src/main/java/oracle/nosql/driver/ops/PreparedStatement.java, driver/src/main/java/oracle/nosql/driver/ops/QueryRequest.java, driver/src/main/java/oracle/nosql/driver/ops/serde/PrepareRequestSerializer.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonProtocol.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonSerializerFactory.java, examples/pom.xml, pom.xml
Add the ability to perform queries in parallel where coordinated threads or processes can each operate on a subset of a table's rows. This feature requires server support
=> Add parallel query function

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/ops/DeleteResult.java, driver/src/main/java/oracle/nosql/driver/ops/GetResult.java, driver/src/main/java/oracle/nosql/driver/ops/PutResult.java, driver/src/main/java/oracle/nosql/driver/ops/WriteMultipleResult.java, driver/src/main/java/oracle/nosql/driver/ops/WriteResult.java, driver/src/main/java/oracle/nosql/driver/ops/serde/BinaryProtocol.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonProtocol.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonSerializerFactory.java, driver/src/test/java/oracle/nosql/driver/BasicTest.java
Added new API to return creation time for a row.
=> CreationTime feature

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/ops/DeleteRequest.java, driver/src/main/java/oracle/nosql/driver/ops/DurableRequest.java, driver/src/main/java/oracle/nosql/driver/ops/MultiDeleteRequest.java, driver/src/main/java/oracle/nosql/driver/ops/PutRequest.java, driver/src/main/java/oracle/nosql/driver/ops/QueryRequest.java, driver/src/main/java/oracle/nosql/driver/ops/WriteRequest.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonSerializerFactory.java, driver/src/main/java/oracle/nosql/driver/values/JsonUtils.java
Fix rowMetadata on a multiDelete operation.
Allow JSON constructs rather than only JSON Object.
=> Add rowMetadat to multi delete request
