.classpath, driver/src/main/java/oracle/nosql/driver/Nson.java, driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/ops/serde/BinaryProtocol.java, driver/src/main/java/oracle/nosql/driver/util/BinaryProtocol.java, driver/src/main/java/oracle/nosql/driver/util/ByteInputStream.java, driver/src/main/java/oracle/nosql/driver/util/ByteOutputStream.java, driver/src/main/java/oracle/nosql/driver/util/NettyByteInputStream.java, driver/src/main/java/oracle/nosql/driver/util/NettyByteOutputStream.java, driver/src/main/java/oracle/nosql/driver/util/NumberUtil.java, driver/src/main/java/oracle/nosql/driver/util/SerializationUtil.java, driver/src/main/java/oracle/nosql/driver/util/SizeOf.java, driver/src/main/java/oracle/nosql/driver/util/TimestampUtil.java, driver/src/main/java/oracle/nosql/driver/values/FieldFinder.java, driver/src/main/java/oracle/nosql/driver/values/FieldValue.java, driver/src/main/java/oracle/nosql/driver/values/FieldValueEventHandler.java, driver/src/main/java/oracle/nosql/driver/values/JsonPrettySerializer.java, driver/src/main/java/oracle/nosql/driver/values/JsonReader.java, driver/src/main/java/oracle/nosql/driver/values/JsonSerializer.java, driver/src/main/java/oracle/nosql/driver/values/JsonUtils.java, driver/src/main/java/oracle/nosql/driver/values/MapValue.java, driver/src/main/java/oracle/nosql/driver/values/TimestampValue.java, driver/src/main/java/oracle/nosql/driver/values/package-info.java, driver/src/test/java/oracle/nosql/driver/TimestampTest.java, driver/src/test/java/oracle/nosql/driver/ValueTest.java
This change makes code sharing with nson relatively seamless
=> Refactor to enable code sharing with nson

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java, driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/http/NoSQLHandleImpl.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClientChannelPoolHandler.java, driver/src/main/java/oracle/nosql/driver/package-info.java
2 somewhat independent pieces of work here:
1. "fix" logging so that it works with logging config files
2. modified netty configuration related to threads to better conform to Netty recommendations and scale more readily without user intervention
Added package-level documentation for above changes
=> Improved netty config and logging

README.md
Also updated the quickstart example to include code to demonstrate Instance and Resource Principal usage.
=> Enhance README to talk about Instance Principal and Resource Principal

driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java
Changed internal channel acquire to do internal retries on acquire errors. Changed the channel acquire timeout to be the lesser of the request timeout and 1000ms. This allows the acquire to retry if there is time left on the request timeout. Logging and error messages have been enhanced.
=> Added retries on internal channel acquire errors.

README.md
I have updated documentation links to the latest release
=> updated doc link

CHANGELOG.md, README.md, driver/pom.xml, driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java, examples/pom.xml, pom.xml
- On-premises only: added support for default namespace in NoSQLHandleConfig
- Updated javadoc for QueryRequest try-with-resources
- Fixed timeout value sent to server on internal retries
=> Preparing for 5.4.9 release

README.md, driver/src/main/java/oracle/nosql/driver/ops/QueryIterableResult.java, driver/src/main/java/oracle/nosql/driver/ops/QueryRequest.java, examples/src/main/java/BasicTableExample.java, examples/src/main/java/DocSnippets.java
More examples in README.md, examples, javadoc.
=> More updates of QueryRequest usage inside try-with-resources block

driver/src/main/java/oracle/nosql/driver/ops/Request.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonProtocol.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonSerializerFactory.java
These are currently meant for testing only.
=> Added hidden options for upcoming cloud DRL

CHANGELOG.md, README.md, driver/pom.xml, driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/httpclient/ResponseHandler.java, driver/src/main/java/oracle/nosql/driver/iam/InstancePrincipalsProvider.java, driver/src/main/java/oracle/nosql/driver/iam/SignatureProvider.java, driver/src/main/java/oracle/nosql/driver/util/HttpRequestUtil.java, examples/pom.xml, pom.xml
Changed internal IAM logic to close channel on SSL errors before doing internal retry
=> Preparing for 5.4.11 release

driver/pom.xml, driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java
This is an issue only in new, unreleased code
=> Retry attempts to acquire a new channel on generic failures

driver/src/test/java/oracle/nosql/driver/OnPremiseTest.java
Adjusted onprem test to check for kv version.
=> Fixed default namespaces test

CHANGELOG.md, README.md, driver/pom.xml, driver/src/main/java/oracle/nosql/driver/Region.java, driver/src/main/java/oracle/nosql/driver/iam/Utils.java, examples/pom.xml, pom.xml
Also updated incorrect realm domain for OC22
=> Preparing for 5.4.13 release

driver/src/main/java/oracle/nosql/driver/Region.java, driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/httpclient/ConnectionPool.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java, driver/src/main/java/oracle/nosql/driver/iam/SecurityTokenSupplier.java, driver/src/main/java/oracle/nosql/driver/query/SortIter.java, driver/src/main/java/oracle/nosql/driver/util/HttpRequestUtil.java, driver/src/main/java/oracle/nosql/driver/util/SimpleRateLimiter.java, driver/src/test/java/oracle/nosql/driver/MultiDeleteTest.java, driver/src/test/java/oracle/nosql/driver/QueryTest.java, driver/src/test/java/oracle/nosql/driver/TimestampTest.java, driver/src/test/java/oracle/nosql/driver/WriteMultipleTest.java
1. Fix unused and redundant imports
2. Use lambda expressions instead of anonymous inner classes
3. Use of assertEquals instead of assertTrue
4. Use StandardCharsets.UTF8
=> Minor - Refactors

driver/src/main/java/oracle/nosql/driver/TableNotReadyException.java, driver/src/main/java/oracle/nosql/driver/ops/TableResult.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonProtocol.java
Add new field SYSTEM("sy") to nson protocol for internal ddl request, fix javadoc warnings
=> Add new field SYSTEM("sy") to nson protocol for internal ddl request

CHANGELOG.md, README.md, driver/pom.xml, driver/src/main/java/oracle/nosql/driver/SDKVersion.java, examples/pom.xml, pom.xml
- Added SDK version number in exception messages
- Modified internal query processing to better support elasticity operations
- Update netty dependency to 4.1.101.Final
=> Preparing for 5.4.14 release

CHANGELOG.md, driver/src/main/java/oracle/nosql/driver/ops/AddReplicaRequest.java, driver/src/main/java/oracle/nosql/driver/ops/DropReplicaRequest.java, driver/src/main/java/oracle/nosql/driver/ops/ReplicaStatsRequest.java, driver/src/main/java/oracle/nosql/driver/ops/serde/nson/NsonSerializerFactory.java
Add the use of ETag to AddReplicaRequest and DropReplicaRequest
=> Add use of ETag to AddReplicaRequest and DropReplicaRequest

driver/src/main/java/oracle/nosql/driver/ops/serde/BinaryProtocol.java
Map ETAG_MISMATCH error to IllegalArgumentException
=> Map ETAG_MISMATCH error to IllegalArgumentException

.gitignore, CHANGELOG.md, README.md, driver/src/main/java/oracle/nosql/driver/httpclient/ConnectionPool.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClient.java, driver/src/main/java/oracle/nosql/driver/httpclient/HttpClientChannelPoolHandler.java, driver/src/main/java/oracle/nosql/driver/iam/FederationRequestHelper.java, driver/src/main/java/oracle/nosql/driver/iam/InstanceMetadataHelper.java, driver/src/main/java/oracle/nosql/driver/iam/InstancePrincipalsProvider.java, driver/src/main/java/oracle/nosql/driver/iam/OkeWorkloadIdentityProvider.java, driver/src/main/java/oracle/nosql/driver/iam/ResourcePrincipalProvider.java, driver/src/main/java/oracle/nosql/driver/iam/ResourcePrincipalTokenSupplier.java, driver/src/main/java/oracle/nosql/driver/iam/SecurityTokenSupplier.java, driver/src/main/java/oracle/nosql/driver/iam/SignatureProvider.java, driver/src/main/java/oracle/nosql/driver/iam/Utils.java, driver/src/test/java/oracle/nosql/driver/iam/ResourcePrincipalProviderTest.java
This is new code and a refactor to share code in order to support OKE workload identities for cloud service authentication. The code change was done by Yang Fei
=> Add support for OKE workload identity authentication in the cloud service

driver/src/main/java/oracle/nosql/driver/ops/Request.java, driver/src/main/java/oracle/nosql/driver/query/ReceiveIter.java
These were found by Akshay while doing some async work
=> Fix a couple of minor, internal-only coding issues found by async work

driver/src/main/java/oracle/nosql/driver/util/LruCache.java
Add a clear() method to LruCache.java
=> Add a clear method to LruCache.java

driver/src/main/java/oracle/nosql/driver/http/Client.java, driver/src/main/java/oracle/nosql/driver/ops/Result.java, driver/src/main/java/oracle/nosql/driver/util/HttpConstants.java
Internal use only at this time, for testing
=> Add mechanism to return server protocol serial version

driver/src/test/java/oracle/nosql/driver/BasicTest.java
Changed minimum kv version for creationTime to 26.1
=> Updated creation time test minimum version
